services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-education
    user: root
    environment:
      SA_PASSWORD: "Admin123--"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    volumes:
      - ./EducationAPIDB.bak:/var/opt/mssql/backup/EducationAPIDB.bak
      - ./restore.sh:/usr/config/restore.sh
      - sqlserver_data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Admin123--", "-Q", "SELECT name FROM sys.databases WHERE name = 'EducationDB'"]
      interval: 10s
      timeout: 10s
      retries: 12
    entrypoint: [ "/bin/bash", "-c" ]
    command: |
      /opt/mssql/bin/sqlservr & 
      sleep 20 && /usr/config/restore.sh || echo "Fallo en restauracion"
      wait

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EducationDB;User Id=sa;Password=Admin123--;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:80"

volumes:
  sqlserver_data: