version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-education
    environment:
      SA_PASSWORD: "Admin123--"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - ./EducationAPIDB.bak:/var/opt/mssql/backup/EducationAPIDB.bak
      - ./restore.sh:/usr/config/restore.sh
      - sqlserver_data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Admin123--", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: 
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr &
        /usr/config/restore.sh
        wait

  api:
    build: .
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=EducationDB;User Id=sa;Password=Admin123--;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:80"

volumes:
  sqlserver_data:
