services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123--
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/backup

  sqlcmd-runner:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlcmd-runner
    depends_on:
      - sqlserver
    volumes:
      - ./mssql/init.sql:/init.sql
      - ./mssql:/backup
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "sleep 30 &&
       /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P Admin123-- -i /init.sql"
    restart: "no"

  educationapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educationapi
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EducationDB;User Id=sa;Password=Admin123--;TrustServerCertificate=True;